spring:
  web:
    resources:
      add-mappings: true
  datasource:
    url: jdbc:mysql://localhost:3306/bjpowernode
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        login-username: jack
        login-password: 123456
      web-stat-filter:
        enabled: true
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        url-pattern: /*
      aop-patterns: happy.controller

  jdbc:
    template:
      query-timeout: 3
mybatis:
  config-location: classpath:mybatis/mybatisConfig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
